spring:
    application:
        name: gateway-service
    
    cloud:
        gateway:
            routes:
                -   id: event_categorie-microservice
                    uri: lb://events-service
                    predicates:
                        - Path=/events/**
                        - Path=/categories/**
                -   id: internaute-microservice
                    uri: lb://internautes-service
                    predicates:
                        - Path=/internautes/**
                -   id: ticket-microservice
                    uri: lb://tickets-service
                    predicates:
                        - Path=/tickets/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true